### ISSUE TITLE
peeflix-server does not run after trying to update on top of previous version

### ISSUE THREAD

**Issue by inglesuniversal** [asapach/peerflix-server#108]
I noticed some updates on your repository, so I wanted to update your script, however, it stops working immediately as soon as I run it... These are the codes I am getting hoping you can give me a single tip to fix this issue and have it working once more...

`/usr/lib/node_modules/peerflix-server/server/engine.js:8
var tryPort = new Promise(function (resolve) {
                  ^
ReferenceError: Promise is not defined
    at Object.<anonymous> (/usr/lib/node_modules/peerflix-server/server/engine.js:8:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/peerflix-server/server/store.js:9:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)`

**Comment by asapach** [comment]
What Node.js version do you have? It requires at least 0.12.
Try running `node --version`
