### ISSUE TITLE
ERR_INVALID_CALLBACK & ERR_HTTP_HEADERS_SENT on Nodjs10.X

### ISSUE THREAD

**Issue by Smax2k** [asapach/peerflix-server#150]
Hello,

I love your app but is not working on my vps on Debian 8 (nodejs 10.x) when i add a torrent.

Server : http://91.134.122.218:9000/

Errors :

`Listening on http://localhost:9000
previous state not found
GET /torrents 304 5.307 ms - -
adding b3a61bdaf92821d3f8ab7772fb66b2550ffa796c
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:135:11)
    at Object.unlink (fs.js:903:14)
    at /usr/lib/node_modules/peerflix-server/server/index.js:91:8
    at /usr/lib/node_modules/peerflix-server/server/store.js:52:9
    at /usr/lib/node_modules/peerflix-server/node_modules/read-torrent/index.js:18:13
    at process._tickCallback (internal/process/next_tick.js:61:11)
_http_outgoing.js:470
    throw new ERR_HTTP_HEADERS_SENT('set');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.res.setHeader (/usr/lib/node_modules/peerflix-server/node_modules/connect/lib/patch.js:134:22)
    at ServerResponse.res.set.res.header (/usr/lib/node_modules/peerflix-server/node_modules/express/lib/response.js:595:10)
    at ServerResponse.res.send (/usr/lib/node_modules/peerflix-server/node_modules/express/lib/response.js:151:12)
    at ServerResponse.res.json (/usr/lib/node_modules/peerflix-server/node_modules/express/lib/response.js:237:15)
    at ServerResponse.res.send (/usr/lib/node_modules/peerflix-server/node_modules/express/lib/response.js:139:21)
    at /usr/lib/node_modules/peerflix-server/server/index.js:87:11
    at /usr/lib/node_modules/peerflix-server/server/store.js:54:9
    at /usr/lib/node_modules/peerflix-server/node_modules/read-torrent/index.js:18:13
    at process._tickCallback (internal/process/next_tick.js:61:11)
`

**Comment by asapach** [comment]
Looks like a compatibility problem with Node 10. I'll take a look at it over the weekend. In the meantime you can try downgrading to Node 8.

**Comment by Smax2k** [comment]
Ok thank you is working now !
