### ISSUE TITLE
500 Internal Server on GET /torrents

### ISSUE THREAD

**Issue by error39** [asapach/peerflix-server#24]
Hi,

After pasting a magnet link or uploading a torrent, not much is happening in the browser.
Output generated by peerflix-server:

info: handshake authorized piUno-zl_Jj65_L54eQs
GET /torrents 200 5ms - 2b
adding 72f242db89e763b6ce390f25d576195c2169b149
POST /upload 200 2247ms - 60b
current state saved
GET /torrents/72f242db89e763b6ce390f25d576195c2169b149 200 2ms - 60b
verifying 72f242db89e763b6ce390f25d576195c2169b149
0 Big.Buck.Bunny.4K.UHD.HFR.60fps.FLAC.WEBDL.2160p.X264_ZMachine.mkv
ready 72f242db89e763b6ce390f25d576195c2169b149

After that it starts throwing the following error over and over again:

TypeError: undefined is not a function
    at module.exports (/usr/local/lib/node_modules/peerflix-server/server/progressbar.js:9:10)
    at serialize (/usr/local/lib/node_modules/peerflix-server/server/index.js:29:15)
    at /usr/local/lib/node_modules/peerflix-server/server/index.js:42:12
    at callbacks (/usr/local/lib/node_modules/peerflix-server/node_modules/express/lib/router/index.js:164:37)
    at param (/usr/local/lib/node_modules/peerflix-server/node_modules/express/lib/router/index.js:138:11)
    at param (/usr/local/lib/node_modules/peerflix-server/node_modules/express/lib/router/index.js:135:11)
    at pass (/usr/local/lib/node_modules/peerflix-server/node_modules/express/lib/router/index.js:145:5)
    at Router._dispatch (/usr/local/lib/node_modules/peerflix-server/node_modules/express/lib/router/index.js:173:5)
    at Object.router (/usr/local/lib/node_modules/peerflix-server/node_modules/express/lib/router/index.js:33:10)
    at next (/usr/local/lib/node_modules/peerflix-server/node_modules/express/node_modules/connect/lib/proto.js:193:15)
GET /torrents/72f242db89e763b6ce390f25d576195c2169b149 500 11ms - 1.05kb

Sorry to bother you, both any suggestions on what's happening here?

Node.js version: v0.12.0
Peerflix version: 0.25.2
Platform: Ubuntu 12.04

Thanks!

**Comment by asapach** [comment]
I haven't tested it on node v0.12 yet. Could you try and downgrade to v0.10 to see if it's causing the issue?

**Comment by error39** [comment]
Okay ,I tried and installed two earlier versions (0.10.0 and 0.11.0) of node using [n](https://github.com/tj/n)

Installing peerflix-server in each version breaks with some warnings and a few errors, probable some unmet version dependancies? (e.g. in 0.10.0: npm ERR! Error: No compatible version found: fluent-ffmpeg@'^2.0.0-rc3')
Is it possible that some dependant npm packages like fluent-ffmpeg don't have the needed version available anymore?

I'm quite new with node and npm so it's all stil a bit of guessing for me..

Appreciate your support, thanks!

**Comment by asapach** [comment]
I'm personally running it on Ubuntu 14.04, Node v0.10.25, npm 2.1.8. I don't get any errors.

`fluent-ffmpeg` is not a critical dependency, it should work without it. Are there any other errors?

**Comment by error39** [comment]
Upgraded default npm which came with 0.10.25 to the latest version and now install just gives a few warnings, but finished successfully. Peerflix working as supposed now as well, so downgrading node and upgrading npm did the trick for me.

Any chance peerflix-server will work in node 0.12.0 in the near future?

Thanks for your support and keep up the good work!

**Comment by asapach** [comment]
Sure, I'll keep this issue open until I upgrade to 0.12.

**Comment by asapach** [comment]
fixed in 0.0.21
