### ISSUE TITLE
EADDRINUSE on swarm start up

### ISSUE THREAD

**Issue by saru95** [asapach/peerflix-server#48]
I get this weird error while starting peerflix-server .
```
saru95:~ sarthakmunshi$ peerflix-server
   info  - socket.io started
previous state not found
GET / 200 42ms - 613b
GET /scripts/3d1ccfc4.scripts.js 200 28ms - 2.15kb
GET /styles/6e9014b8.main.css 200 31ms - 2.09kb
GET /styles/15d7b359.vendor.css 200 33ms - 135.19kb
GET /scripts/945feeed.vendor.js 200 529ms - 281.71kb
GET /views/main.html 200 2ms - 3.45kb
   info  - handshake authorized 8HT9SDaBVVDKoRWrgaWI
GET /torrents 200 3ms - 2b
GET /images/169ad458.logo.svg 200 16ms - 973b
GET /favicon.ico?new 200 3ms - 318b
GET /bower_components/font-awesome/fonts/fontawesome-webfont.woff?v=4.2.0 200 6ms - 63.92kb
GET /torrents 304 1ms
adding 582e0b49e65ffad71b1285b8f21da8df57866435
POST /torrents 200 6ms - 60b

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1042:14)
    at listen (net.js:1064:10)
    at Server.listen (net.js:1138:5)
    at join (/usr/local/lib/node_modules/peerflix-server/node_modules/torrent-stream/node_modules/peer-wire-swarm/index.js:87:10)
    at Swarm.listen (/usr/local/lib/node_modules/peerflix-server/node_modules/torrent-stream/node_modules/peer-wire-swarm/index.js:211:2)
    at EventEmitter.engine.listen (/usr/local/lib/node_modules/peerflix-server/node_modules/torrent-stream/index.js:718:9)
    at module.exports (/usr/local/lib/node_modules/peerflix-server/server/engine.js:50:10)
    at /usr/local/lib/node_modules/peerflix-server/server/store.js:48:17
    at /usr/local/lib/node_modules/peerflix-server/node_modules/read-torrent/index.js:18:13
saru95:~ sarthakmunshi$ peerflix-server
   info  - socket.io started
previous state not found
GET / 304 31ms
GET /styles/15d7b359.vendor.css 304 4ms
GET /styles/6e9014b8.main.css 304 3ms
GET /scripts/945feeed.vendor.js 304 4ms
GET /scripts/3d1ccfc4.scripts.js 304 3ms
GET /views/main.html 304 2ms
   info  - handshake authorized bX71hxJ5LP3Od38pgtDD
GET /torrents 200 2ms - 2b
GET /bower_components/font-awesome/fonts/fontawesome-webfont.woff?v=4.2.0 304 4ms
GET /favicon.ico?new 200 6ms - 318b
GET /torrents 304 1ms
adding 582e0b49e65ffad71b1285b8f21da8df57866435
POST /torrents 200 7ms - 60b

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1042:14)
    at listen (net.js:1064:10)
    at Server.listen (net.js:1138:5)
    at join (/usr/local/lib/node_modules/peerflix-server/node_modules/torrent-stream/node_modules/peer-wire-swarm/index.js:87:10)
    at Swarm.listen (/usr/local/lib/node_modules/peerflix-server/node_modules/torrent-stream/node_modules/peer-wire-swarm/index.js:211:2)
    at EventEmitter.engine.listen (/usr/local/lib/node_modules/peerflix-server/node_modules/torrent-stream/index.js:718:9)
    at module.exports (/usr/local/lib/node_modules/peerflix-server/server/engine.js:50:10)
    at /usr/local/lib/node_modules/peerflix-server/server/store.js:48:17
    at /usr/local/lib/node_modules/peerflix-server/node_modules/read-torrent/index.js:18:13
```

**Comment by asapach** [comment]
EADDRINUSE means that somebody else is using the port we're trying to bind to. This is happening when the swarm is starting up on port 6881. Please check for other running torrent clients.

**Comment by saru95** [comment]
i was running normal peerflix on another tab for testing .
