### ISSUE TITLE
[HELP] i can't start peerflix-server 

### ISSUE THREAD

**Issue by yas9999** [asapach/peerflix-server#71]
Hello,
i can't start peerflix-server it show me this message :( 

sudo peerflix-server
   info  - socket.io started
   warn  - error raised: Error: listen EADDRINUSE
resuming from previous state
loading a5a8174f6820867bd7d273b07988e5bb697bb49c

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1039:14)
    at listen (net.js:1061:10)
    at Server.listen (net.js:1135:5)
    at join (/usr/local/lib/node_modules/peerflix-server/node_modules/torrent-stream/node_modules/peer-wire-swarm/index.js:87:10)
    at Swarm.listen (/usr/local/lib/node_modules/peerflix-server/node_modules/torrent-stream/node_modules/peer-wire-swarm/index.js:211:2)
    at EventEmitter.engine.listen (/usr/local/lib/node_modules/peerflix-server/node_modules/torrent-stream/index.js:718:9)
    at module.exports (/usr/local/lib/node_modules/peerflix-server/server/engine.js:50:10)
    at EventEmitter._.extend.load (/usr/local/lib/node_modules/peerflix-server/server/store.js:77:13)
    at /usr/local/lib/node_modules/peerflix-server/server/store.js:108:17

Please help me

**Comment by asapach** [comment]
It looks like you have something else listening on port 6881. Do you have another torrent client running? Try commenting out this piece: https://github.com/asapach/peerflix-server/blob/master/server/engine.js#L50-52

**Comment by yas9999** [comment]
Thank you so much @asapach :+1: 
i guess transmission-daemon was listening on port 6881 

Best regards,
