### ISSUE TITLE
Getting a 500 error when sending a POST to /torrents

### ISSUE THREAD

**Issue by kirpaldemian** [asapach/peerflix-server#79]
I'm trying to POST a magnet link to localhost:9000/torrents, and keep getting a 500 error. Other endpoints such as POST /torrents/{infoHash}/pause work. Here is the err message:

`TypeError: path must be a string
    at Object.fs.open (fs.js:418:11)
    at Object.fs.readFile (fs.js:206:6)
    at readTorrent (/usr/local/lib/node_modules/peerflix-server/node_modules/read-torrent/index.js:54:8)
    at EventEmitter._.extend.add (/usr/local/lib/node_modules/peerflix-server/server/store.js:36:5)
    at api.post.file (/usr/local/lib/node_modules/peerflix-server/server/index.js:67:9)
    at callbacks (/usr/local/lib/node_modules/peerflix-server/node_modules/express/lib/router/index.js:164:37)
    at param (/usr/local/lib/node_modules/peerflix-server/node_modules/express/lib/router/index.js:138:11)
    at pass (/usr/local/lib/node_modules/peerflix-server/node_modules/express/lib/router/index.js:145:5)
    at Router._dispatch (/usr/local/lib/node_modules/peerflix-server/node_modules/express/lib/router/index.js:
173:5)
    at Object.router (/usr/local/lib/node_modules/peerflix-server/node_modules/express/lib/router/index.js:33:
10)
POST /torrents 500 4ms - 956b`

**Comment by asapach** [comment]
You need to pass the `link` field in the request as JSON: 
```
Host: ...
Content-Type: application/json;charset=utf-8

{"link":"magnet:..."}
```

**Comment by kirpaldemian** [comment]
This fixed it, thank you.
